# Enable logging for the dev environment
logging:
    level:
        # All logs have a minimum level of INFO
        root: INFO
        # The logs related to our codes have a level of DEBUG
        '[com.cs308.eureka_server]': DEBUG
        # The logs related to Eureka have a level of DEBUG
        '[org.springframework.cloud.netflix.eureka]': DEBUG
    file:
        # Path for the Docker container's file system
        path: /app/log/prod
        name: eureka-server.log
    